### ISSUE TITLE
Exception in thread "main" java.lang

### ISSUE THREAD

**Issue by kaibakev1984** [kaibakev1984/AutomationTestingFramework#1]
When I make a click in  _run scenario_, system throws this exception instead to run the project:
~~~
Exception in thread "main" java.lang.NoSuchMethodError: cucumber.runtime.formatter.PluginFactory.isStepDefinitionReporterName(Ljava/lang/String;)Z
	at io.cucumber.core.options.RuntimeOptionsBuilder$ParsedPluginData.addPluginName(RuntimeOptionsBuilder.java:218)
	at io.cucumber.core.options.RuntimeOptionsBuilder.addPluginName(RuntimeOptionsBuilder.java:73)
	at io.cucumber.core.options.RuntimeOptionsParser.parse(RuntimeOptionsParser.java:90)
	at io.cucumber.core.options.CommandlineOptionsParser.parse(CommandlineOptionsParser.java:25)
	at io.cucumber.core.options.CommandlineOptionsParser.parse(CommandlineOptionsParser.java:29)
	at io.cucumber.core.cli.Main.run(Main.java:29)
	at io.cucumber.core.cli.Main.main(Main.java:14)
~~~

**Comment by kaibakev1984** [comment]
Some dependencies were changed in _pom.xml_ to solve it.
